### ISSUE TITLE
summarize packages failed on exit

### ISSUE THREAD

**Issue by udance4ever** [paguilar/br-pbuilder#3]
ok - the build halted (this is a verified clean build last I tried building serially) - is there an easy way to list which pkgs failed? (scroll buffer in Termius is truncated to reduce memory usage so iPadOS doesn’t kill app!)
```
Freeing thread at position 0
>>> llvm 18.1.2 Installing to staging directory
>>> llvm 18.1.2 Fixing libtool files
>>> llvm 18.1.2 Installing to target
Package 'llvm' built in 1231.442512 secs
Freeing thread at position 5
Halting build due to previous errors!
===== Total elapsed time: 4206.023315
Build failed!!!
pbuilder: ERR: Failed to execute graph
make: *** [Makefile:939: pbuilder] Error 1
make: Leaving directory '/build/buildroot'
make: *** [Makefile:136: x86_64-build] Error 2
```

**Comment by paguilar** [comment]
Currently the only way to easily find which pkg failed is to look at the output. May be a few hundreds lines could be sufficient, even less if you build without debug info (without the -l when executing br-pbuilder).

**Comment by paguilar** [comment]
This commit [e49a62f](https://github.com/paguilar/br-pbuilder/commit/e49a62fe372a924cf057f7ac28207a2d7cd3b4a9) should display the list of failed packages at the end of the process so they're not missed when the terminal truncates its output to a few lines.

**Comment by udance4ever** [comment]
thanks for this enhancement!  I assume this works and pulling this commit in the latest commit of the `br-pbuilder` branch.

I’m going to close this issue and will reopen it in the event there are any issues.

**Comment by udance4ever** [comment]
while I would have preferred **not** to have any errors - I can confirm the enhancement works.
