### ISSUE TITLE
finalization targets produce zero length log files

### ISSUE THREAD

**Issue by udance4ever** [paguilar/br-pbuilder#7]
Finalization is a 20 min process (on an M1) so it would be nice to see log files and follow its progress (as it also looks hung the entire time):
```
Package 'host-finalize' built in 10.478227 secs
Package 'staging-finalize' built in 6.546078 secs
Package 'target-finalize' built in 118.130936 secs
Package 'target-post-image' built in 1051.830706 secs
```
log files:
```
-rw-r--r--. 1 squatter squatter        0 Sep 20 19:10 host-finalize.log
-rw-r--r--. 1 squatter squatter        0 Sep 20 19:10 staging-finalize.log
-rw-r--r--. 1 squatter squatter        0 Sep 20 19:10 target-finalize.log
-rw-r--r--. 1 squatter squatter        0 Sep 20 19:12 target-post-image.log
```
Perhaps the output file needs a final flush?

**Comment by paguilar** [comment]
This commit [1b09261](https://github.com/paguilar/br-pbuilder/commit/1b09261da4e9f396d261c9dd76fc174223ef3b53) redirects the output of these targets in the same way as when building any standard package.

It also adds a missing BR2_EXTERNAL env variable that could generate issues when building these targets and an external tree is present.

This could improve the situation reported here (#1 )

**Comment by udance4ever** [comment]
tested and works!
